name: Testing

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.4, 8.3, 8.2, 8.1, 8.0 ]
        laravel: [ 12.*, 11.*, 10.*, 9.* ]
        include:
          - laravel: 12.*
            testbench: 10.*
          - laravel: 11.*
            testbench: 9.*
          - laravel: 10.*
            testbench: 8.*
          - laravel: 9.*
            testbench: 7.*
        exclude:
          # Laravel 12: PHP 8.2+ only
          - laravel: 12.*
            php: 8.1
          - laravel: 12.*
            php: 8.0
          # Laravel 11: PHP 8.2+ only
          - laravel: 11.*
            php: 8.1
          - laravel: 11.*
            php: 8.0
          # Laravel 10: PHP 8.1+ only
          - laravel: 10.*
            php: 8.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set correct PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, json

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit
